"""Add LIMS tables for sample tracking, inventory, calibration, and workflow management

Revision ID: 141745a63b7a
Revises: 
Create Date: 2025-11-27 04:04:22.963651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141745a63b7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.LargeBinary(), nullable=True),
    sa.Column('public_key', sa.LargeBinary(), nullable=True),
    sa.Column('ca_cert', sa.LargeBinary(), nullable=True),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_actor'), 'audit', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_event'), 'audit', ['event'], unique=False)
    op.create_index(op.f('ix_audit_hash'), 'audit', ['hash'], unique=False)
    op.create_index(op.f('ix_audit_subject'), 'audit', ['subject'], unique=False)
    op.create_index(op.f('ix_audit_ts'), 'audit', ['ts'], unique=False)
    op.create_table('config_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_snapshots_config_hash'), 'config_snapshots', ['config_hash'], unique=False)
    op.create_index(op.f('ix_config_snapshots_snapshot_id'), 'config_snapshots', ['snapshot_id'], unique=True)
    op.create_index(op.f('ix_config_snapshots_timestamp'), 'config_snapshots', ['timestamp'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=False),
    sa.Column('container_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containers_container_id'), 'containers', ['container_id'], unique=True)
    op.create_index(op.f('ix_containers_location'), 'containers', ['location'], unique=False)
    op.create_table('device_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_calibration_date', sa.Date(), nullable=True),
    sa.Column('next_calibration_due', sa.Date(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_status_device_id'), 'device_status', ['device_id'], unique=True)
    op.create_index(op.f('ix_device_status_last_calibration_date'), 'device_status', ['last_calibration_date'], unique=False)
    op.create_index(op.f('ix_device_status_next_calibration_due'), 'device_status', ['next_calibration_due'], unique=False)
    op.create_index(op.f('ix_device_status_status'), 'device_status', ['status'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_items_current_stock'), 'inventory_items', ['current_stock'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_code'), 'inventory_items', ['item_code'], unique=True)
    op.create_index(op.f('ix_inventory_items_location'), 'inventory_items', ['location'], unique=False)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_vendor_id'), 'vendors', ['vendor_id'], unique=True)
    op.create_table('labs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_id', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_lab_id'), 'labs', ['lab_id'], unique=True)
    op.create_index(op.f('ix_labs_organization_id'), 'labs', ['organization_id'], unique=False)
    op.create_table('stock_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_remaining', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_lots_expiration_date'), 'stock_lots', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_stock_lots_item_id'), 'stock_lots', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_lots_lot_number'), 'stock_lots', ['lot_number'], unique=True)
    op.create_index(op.f('ix_stock_lots_received_date'), 'stock_lots', ['received_date'], unique=False)
    op.create_index(op.f('ix_stock_lots_status'), 'stock_lots', ['status'], unique=False)
    op.create_index(op.f('ix_stock_lots_vendor_id'), 'stock_lots', ['vendor_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('lab_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_lab_id'), 'nodes', ['lab_id'], unique=False)
    op.create_index(op.f('ix_nodes_last_heartbeat'), 'nodes', ['last_heartbeat'], unique=False)
    op.create_index(op.f('ix_nodes_node_id'), 'nodes', ['node_id'], unique=True)
    op.create_index(op.f('ix_nodes_status'), 'nodes', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('password_history', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('lab_id', sa.UUID(), nullable=True),
    sa.Column('sso_provider', sa.String(length=100), nullable=True),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('calibration_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('calibration_date', sa.DateTime(), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('certificate_path', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_entries_calibration_date'), 'calibration_entries', ['calibration_date'], unique=False)
    op.create_index(op.f('ix_calibration_entries_device_id'), 'calibration_entries', ['device_id'], unique=False)
    op.create_index(op.f('ix_calibration_entries_next_due_date'), 'calibration_entries', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_calibration_entries_status'), 'calibration_entries', ['status'], unique=False)
    op.create_table('device_hubs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hub_id', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('device_registry', sa.JSON(), nullable=False),
    sa.Column('health_status', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_hubs_hub_id'), 'device_hubs', ['hub_id'], unique=True)
    op.create_index(op.f('ix_device_hubs_node_id'), 'device_hubs', ['node_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('user_email', 'role_id')
    )
    op.create_table('workflow_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_name', 'version', name='uq_workflow_name_version')
    )
    op.create_index('idx_workflow_active', 'workflow_versions', ['workflow_name', 'is_active'], unique=False)
    op.create_index(op.f('ix_workflow_versions_created_at'), 'workflow_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_versions_is_active'), 'workflow_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_workflow_versions_workflow_name'), 'workflow_versions', ['workflow_name'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_id'), 'batches', ['batch_id'], unique=True)
    op.create_index(op.f('ix_batches_project_id'), 'batches', ['project_id'], unique=False)
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_snapshot_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['config_snapshot_id'], ['config_snapshots.id'], ),
    sa.ForeignKeyConstraint(['operator'], ['users.email'], ),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_run_id'), 'workflow_executions', ['run_id'], unique=True)
    op.create_index(op.f('ix_workflow_executions_started_at'), 'workflow_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_version_id'), 'workflow_executions', ['workflow_version_id'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=255), nullable=False),
    sa.Column('lot_number', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('container_id', sa.UUID(), nullable=True),
    sa.Column('parent_sample_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['parent_sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_batch_id'), 'samples', ['batch_id'], unique=False)
    op.create_index(op.f('ix_samples_container_id'), 'samples', ['container_id'], unique=False)
    op.create_index(op.f('ix_samples_created_at'), 'samples', ['created_at'], unique=False)
    op.create_index(op.f('ix_samples_lot_number'), 'samples', ['lot_number'], unique=False)
    op.create_index(op.f('ix_samples_parent_sample_id'), 'samples', ['parent_sample_id'], unique=False)
    op.create_index(op.f('ix_samples_project_id'), 'samples', ['project_id'], unique=False)
    op.create_index(op.f('ix_samples_sample_id'), 'samples', ['sample_id'], unique=True)
    op.create_index(op.f('ix_samples_status'), 'samples', ['status'], unique=False)
    op.create_table('sample_lineage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_sample_id', sa.UUID(), nullable=False),
    sa.Column('child_sample_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['child_sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['parent_sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sample_lineage_child', 'sample_lineage', ['child_sample_id'], unique=False)
    op.create_index('idx_sample_lineage_parent', 'sample_lineage', ['parent_sample_id'], unique=False)
    op.create_index(op.f('ix_sample_lineage_child_sample_id'), 'sample_lineage', ['child_sample_id'], unique=False)
    op.create_index(op.f('ix_sample_lineage_parent_sample_id'), 'sample_lineage', ['parent_sample_id'], unique=False)
    op.create_table('workflow_sample_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_sample_assignments_sample_id'), 'workflow_sample_assignments', ['sample_id'], unique=False)
    op.create_index(op.f('ix_workflow_sample_assignments_workflow_execution_id'), 'workflow_sample_assignments', ['workflow_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_sample_assignments_workflow_execution_id'), table_name='workflow_sample_assignments')
    op.drop_index(op.f('ix_workflow_sample_assignments_sample_id'), table_name='workflow_sample_assignments')
    op.drop_table('workflow_sample_assignments')
    op.drop_index(op.f('ix_sample_lineage_parent_sample_id'), table_name='sample_lineage')
    op.drop_index(op.f('ix_sample_lineage_child_sample_id'), table_name='sample_lineage')
    op.drop_index('idx_sample_lineage_parent', table_name='sample_lineage')
    op.drop_index('idx_sample_lineage_child', table_name='sample_lineage')
    op.drop_table('sample_lineage')
    op.drop_index(op.f('ix_samples_status'), table_name='samples')
    op.drop_index(op.f('ix_samples_sample_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_project_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_parent_sample_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_lot_number'), table_name='samples')
    op.drop_index(op.f('ix_samples_created_at'), table_name='samples')
    op.drop_index(op.f('ix_samples_container_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_batch_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_workflow_executions_workflow_version_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_started_at'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_run_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_index(op.f('ix_batches_project_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_workflow_versions_workflow_name'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_is_active'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_created_at'), table_name='workflow_versions')
    op.drop_index('idx_workflow_active', table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_device_hubs_node_id'), table_name='device_hubs')
    op.drop_index(op.f('ix_device_hubs_hub_id'), table_name='device_hubs')
    op.drop_table('device_hubs')
    op.drop_index(op.f('ix_calibration_entries_status'), table_name='calibration_entries')
    op.drop_index(op.f('ix_calibration_entries_next_due_date'), table_name='calibration_entries')
    op.drop_index(op.f('ix_calibration_entries_device_id'), table_name='calibration_entries')
    op.drop_index(op.f('ix_calibration_entries_calibration_date'), table_name='calibration_entries')
    op.drop_table('calibration_entries')
    op.drop_table('users')
    op.drop_index(op.f('ix_nodes_status'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_node_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_last_heartbeat'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_lab_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_stock_lots_vendor_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_status'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_received_date'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_lot_number'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_item_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_expiration_date'), table_name='stock_lots')
    op.drop_table('stock_lots')
    op.drop_index(op.f('ix_labs_organization_id'), table_name='labs')
    op.drop_index(op.f('ix_labs_lab_id'), table_name='labs')
    op.drop_table('labs')
    op.drop_index(op.f('ix_vendors_vendor_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_location'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_code'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_current_stock'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_device_status_status'), table_name='device_status')
    op.drop_index(op.f('ix_device_status_next_calibration_due'), table_name='device_status')
    op.drop_index(op.f('ix_device_status_last_calibration_date'), table_name='device_status')
    op.drop_index(op.f('ix_device_status_device_id'), table_name='device_status')
    op.drop_table('device_status')
    op.drop_index(op.f('ix_containers_location'), table_name='containers')
    op.drop_index(op.f('ix_containers_container_id'), table_name='containers')
    op.drop_table('containers')
    op.drop_index(op.f('ix_config_snapshots_timestamp'), table_name='config_snapshots')
    op.drop_index(op.f('ix_config_snapshots_snapshot_id'), table_name='config_snapshots')
    op.drop_index(op.f('ix_config_snapshots_config_hash'), table_name='config_snapshots')
    op.drop_table('config_snapshots')
    op.drop_index(op.f('ix_audit_ts'), table_name='audit')
    op.drop_index(op.f('ix_audit_subject'), table_name='audit')
    op.drop_index(op.f('ix_audit_hash'), table_name='audit')
    op.drop_index(op.f('ix_audit_event'), table_name='audit')
    op.drop_index(op.f('ix_audit_actor'), table_name='audit')
    op.drop_table('audit')
    # ### end Alembic commands ###
