from enum import Enum

class ErrorCode(str, Enum):
    # Hardware Errors
    HARDWARE_TIMEOUT = "HARDWARE_TIMEOUT"
    HARDWARE_CONNECTION_FAILED = "HARDWARE_CONNECTION_FAILED"
    HARDWARE_CONFIG_ERROR = "HARDWARE_CONFIG_ERROR"
    HARDWARE_SAFETY_INTERLOCK = "HARDWARE_SAFETY_INTERLOCK"
    HARDWARE_NOT_IMPLEMENTED = "HARDWARE_NOT_IMPLEMENTED"

    # Workflow Errors
    WORKFLOW_VALIDATION_ERROR = "WORKFLOW_VALIDATION_ERROR"
    WORKFLOW_STEP_FAILED = "WORKFLOW_STEP_FAILED"
    WORKFLOW_TIMEOUT = "WORKFLOW_TIMEOUT"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"

    # DB/Data Errors
    DB_INTEGRITY_ERROR = "DB_INTEGRITY_ERROR"
    DB_CONNECTION_ERROR = "DB_CONNECTION_ERROR"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

    # Auth/Security Errors
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_LOCKED_OUT = "AUTH_LOCKED_OUT"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"

    # AI Errors
    AI_INFERENCE_FAILED = "AI_INFERENCE_FAILED"
    AI_MODEL_NOT_READY = "AI_MODEL_NOT_READY"
    AI_INPUT_INVALID = "AI_INPUT_INVALID"

    # General
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
